POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"nasuru",
    "email":"nasuru@gmail.com",
    "nama_lengkap":"nasuru nasuru",
    "id_institusi":"uaiy98wha",
    "password":"nasuru123",
    "nomor":"0812821287",
    "photo":"/photo1"
}

###
GET http://localhost:3000/login/1

###
GET http://localhost:3000/admin/inventors

###
GET http://localhost:3000/admin/penguji

###
GET http://localhost:3000/admin/alat

###
GET http://localhost:3000/admin/institusi

###
GET http://localhost:3000/admin/aspek

###
GET http://localhost:3000/admin/parameter

###
GET http://localhost:3000/admin/data-aspek

###
GET http://localhost:3000/admin/transaksi

###
GET http://localhost:3000/admin/pengujian

###
GET http://localhost:3000/admin/inventors/1

###
POST http://localhost:3000/admin/inventors
Content-Type: application/json

{
    "username":"nasuru",
    "email":"nasuru@gmail.com",
    "nama_lengkap":"nasuru nasuru",
    "id_institusi":"uaiy98wha",
    "password":"nasuru123",
    "nomor":"0812821287",
    "photo":"/photo1"
}

###
PUT http://localhost:3000/admin/inventors/1
Content-Type: application/json

{
    "username":"nasuru update",
    "email":"nasuru@gmail.com",
    "nama_lengkap":"nasuru nasuru",
    "id_institusi":"uaiy98wha",
    "password":"nasuru123",
    "nomor":"0812821287",
    "photo":"/photo2"
}

###
DELETE http://localhost:3000/admin/inventors/1